### PR TITLE
Update maximum vertically stable elongation surrogate model for m_s = 0.0

### LINKED ISSUE #836: Update maximum vertically stable elongation surrogate model
## Description of issue / requirement to address

`estimate_kappa_95` doesn't quite use the recommended values for m_s=0, which is becoming popular in EU-DEMO following the introduction of in-vessel VS coils.

## Proposed solution

Need to update the fit for the "correct" data points and do the same in PROCESS.

## Alternative solutions

Present model underestimates kappa_95 for A=2.6 m_s < 0.2

### PR DESCRIPTION
**Pull request by CoronelBuendia**
## Linked Issues

Closes #836 

## Description
Fixes the `estimate_kappa_95` surrogate model by adding recommended data points for m_s=0 and a correction for the A=2.6, m_s=0.0 corner point which is poorly fit (1.81+ != 1.80).

Adds some warnings if A or m_s are outside the model ranges.

## Interface Changes
None. results will change.

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `flake8` and `black .`
- [x] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Review by je-cook — APPROVED** [review]
From what I can glean from this, look fine. Are we porting this over at some point?

**Comment by CoronelBuendia** [comment]
> From what I can glean from this, look fine. Are we porting this over at some point?

Perhaps, but really it needs to go into PROCESS, @ajpearcey this is an update on that model I passed over a while back. Perhaps I could slot it in a PR for PROCESS? Might need you to walk me through the procedure.

**Comment by CoronelBuendia** [comment]
I could put this in EUDEMO tools or equilibria for the time being? Does feel strange to update BLUEPRINT... thoughts @je-cook ?

**Comment by je-cook** [comment]
Yeah thats probably best. Poking @ajpearcey again if he has any comment :slightly_smiling_face:

**Comment by ajpearcey** [comment]
If this is an update to the elongation scaling implemented in PROCESS we can certainly update it. Id recommend opening an issue on the PROCESS gitlab requesting the update and assign the issue to me.

**Review by je-cook — APPROVED** [review]

**Comment by je-cook** [comment]
TODO create an issue of PROCESS to add or update this model

**Pull request merged**
