### PR TITLE
Update matplotlib to 3.5.1

### LINKED ISSUE #994: Update matplotlib
## Description of issue / requirement to address

As BLUEPRINT is now removed we should update matplotlib (#234) below are the currently failing tests on the most recent mpl:

```
FAILED tests/balance_of_plant/test_plotting.py::TestSuperSankey::test_sankey_ring - AssertionError: assert False
FAILED tests/equilibria/test_constraints.py::TestWeightedConstraints::test_constraint_weights - AttributeError: 'list' object has no attribute 'T'
FAILED tests/equilibria/test_find.py::TestFindLCFSSeparatrix::test_double_null - AttributeError: 'list' object has no attribute 'T'
FAILED tests/equilibria/test_equilibrium.py::TestEquilibrium::test_double_null - AttributeError: 'list' object has no attribute 'T'
FAILED tests/equilibria/test_equilibrium.py::TestEquilibrium::test_qpsi_calculation_modes - AttributeError: 'list' object has no attribute 'T'
FAILED tests/equilibria/test_equilibrium.py::TestEqReadWrite::test_read_write[0] - AttributeError: 'list' object has no attribute 'T'
FAILED tests/equilibria/test_equilibrium.py::TestEqReadWrite::test_read_write[1] - AttributeError: 'list' object has no attribute 'T'
FAILED tests/equilibria/test_st_equilibrium.py::TestSTEquilibrium::test_equilibrium - AttributeError: 'list' object has no attribute 'T'
FAILED tests/equilibria/test_equilibrium.py::TestQBenchmark::test_q_benchmark - AttributeError: 'list' object has no attribute 'T'
FAILED tests/equilibria/test_find.py::TestFindLCFSSeparatrix::test_other_grid - AttributeError: 'list' object has no attribute 'T'
FAILED tests/geometry/test_deprecated_loop.py::Test3Dplotting::test_looks_good - RecursionError: maximum recursion depth exceeded
FAILED tests/geometry/test_deprecated_loop.py::Test3Dplotting::test_edges_again - RecursionError: maximum recursion depth exceeded
FAILED tests/structural/test_crosssection.py::TestIbeam::test_plot - AttributeError: 'BluemiraFace' object has no attribute 'plot'
FAILED tests/structural/test_model.py::TestCompoundDeflection::test_fixedfixed - AttributeError: 'Element' object has no attribute 'max_deflection'
FAILED tests/structural/test_model.py::TestCompoundDeflection::test_cantilever - AttributeError: 'Element' object has no attribute 'max_deflection'
FAILED tests/structural/test_model.py::TestGravityLoads::test_angled_cantilever - AttributeError: 'Element' object has no attribute 'max_deflection'
FAILED tests/structural/test_symmetry.py::TestCyclicSymmetry::test_symmetry - AttributeError: 'Element' object has no attribute 'max_deflection'
ERROR tests/builders/EUDEMO/test_reactor.py::TestEUDEMO::test_tf_build - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2218: ordinal not in ...
ERROR tests/builders/EUDEMO/test_reactor.py::TestEUDEMO::test_show_cad - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2218: ordinal not in ...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_no_BuilderError_on_init_given_valid_params - AttributeError: 'list' object ha...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_new_builder_sets_leg_lengths - AttributeError: 'list' object has no attribute...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_dome_does_not_intersect_separatrix - AttributeError: 'list' object has no att...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_baffle_and_target_intersect[OUTER] - AttributeError: 'list' object has no att...
ERROR tests/builders/EUDEMO/ivc/test_ivc.py::TestInVesselComponentBuilder::test_wall_boundary_is_cut_below_x_point_in_z_axis - AttributeError: 'list' object has no...
ERROR tests/builders/EUDEMO/test_reactor.py::TestEUDEMO::test_pf_coils_built - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2218: ordinal n...
ERROR tests/builders/EUDEMO/test_reactor.py::TestEUDEMO::test_tf_save - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2218: ordinal not in r...
ERROR tests/builders/EUDEMO/test_reactor.py::TestEUDEMO::test_show_segment_cad - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2218: ordinal...
ERROR tests/builders/EUDEMO/test_reactor.py::TestEUDEMO::test_plasma_build - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2218: ordinal not...
ERROR tests/builders/EUDEMO/test_reactor.py::TestEUDEMO::test_plot_xy - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2218: ordinal not in r...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_BuilderError_given_required_param_missing[div_L2D_ob] - AttributeError: 'list...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_target_length_set_by_parameter - AttributeError: 'list' object has no attribu...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_inner_baffle_has_end_at_lower_x_limit - AttributeError: 'list' object has no ...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_BuilderError_on_call_given_x_limits_empty[x_lims0] - AttributeError: 'list' o...
ERROR tests/builders/EUDEMO/ivc/test_ivc.py::TestInVesselComponentBuilder::test_contains_one_wall_component - AttributeError: 'list' object has no attribute 'T'
ERROR tests/builders/EUDEMO/ivc/test_ivc.py::TestInVesselComponentBuilder::test_component_tree_structure - AttributeError: 'list' object has no attribute 'T'
ERROR tests/builders/EUDEMO/ivc/test_ivc.py::TestInVesselComponentBuilder::test_BuilderError_if_wall_does_not_enclose_x_point - AttributeError: 'list' object has n...
ERROR tests/builders/EUDEMO/test_reactor.py::TestEUDEMO::test_plot_xz - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 2218: ordinal not in r...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_BuilderError_given_required_param_missing[div_L2D_ib] - AttributeError: 'list...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_targets_intersect_separatrix - AttributeError: 'list' object has no attribute...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_SN_lower_dome_has_turning_point_below_x_point - AttributeError: 'list' object...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_setting_xz_limits_after_init_sets_start_and_end_points - AttributeError: 'lis...
ERROR tests/builders/EUDEMO/ivc/test_ivc.py::TestInVesselComponentBuilder::test_contains_one_divertor_component_given_SN_plasma - AttributeError: 'list' object has...
ERROR tests/equilibria/test_find.py::TestGetLegs::test_single_null[2] - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_find.py::TestGetLegs::test_single_null[3] - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_find.py::TestGetLegs::test_single_null[5] - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_find.py::TestGetLegs::test_single_one_layer - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_find.py::TestGetLegs::test_double_null[2] - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_find.py::TestGetLegs::test_double_null[3] - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_find.py::TestGetLegs::test_double_null[5] - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_find.py::TestGetLegs::test_double_one_layer - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_flux_surfaces.py::TestOpenFluxSurfaceStuff::test_bad_geometry - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_flux_surfaces.py::TestOpenFluxSurfaceStuff::test_connection_length - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_flux_surfaces.py::TestFieldLine::test_connection_length - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_equilibrium.py::TestFields::test_Bx - AttributeError: 'list' object has no attribute 'T'
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_BuilderError_given_required_param_missing[div_open] - AttributeError: 'list' ...
ERROR tests/equilibria/test_equilibrium.py::TestFields::test_Bz - AttributeError: 'list' object has no attribute 'T'
ERROR tests/equilibria/test_equilibrium.py::TestFields::test_Bp - AttributeError: 'list' object has no attribute 'T'
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_dome_intersects_targets - AttributeError: 'list' object has no attribute 'T'
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_baffle_and_target_intersect[INNER] - AttributeError: 'list' object has no att...
ERROR tests/equilibria/test_equilibrium.py::TestFields::test_psi - AttributeError: 'list' object has no attribute 'T'
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_BuilderError_on_call_given_x_limits_empty[x_lims2] - AttributeError: 'list' o...
ERROR tests/equilibria/test_equilibrium.py::TestFields::test_out_of_bounds - AttributeError: 'list' object has no attribute 'T'
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_BuilderError_given_required_param_missing[div_Ltarg] - AttributeError: 'list'...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_dome_added_to_divertor - AttributeError: 'list' object has no attribute 'T'
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_outer_baffle_has_end_at_upper_x_limit - AttributeError: 'list' object has no ...
ERROR tests/builders/EUDEMO/ivc/test_divertor.py::TestDivertorSilhouetteBuilder::test_BuilderError_on_call_given_x_limits_empty[None] - AttributeError: 'list' obje...
ERROR tests/radiation_transport/test_advective_transport.py::TestChargedParticleRecursionSN::test_recursion - AttributeError: 'list' object has no attribute 'T'
ERROR tests/radiation_transport/test_advective_transport.py::TestChargedParticleRecursionSN::test_n_intersections - AttributeError: 'list' object has no attribute 'T'
ERROR tests/radiation_transport/test_advective_transport.py::TestChargedParticleRecursionSN::test_integrals - AttributeError: 'list' object has no attribute 'T'
ERROR tests/radiation_transport/test_advective_transport.py::TestChargedParticleRecursionSN::test_geometry_handling - AttributeError: 'list' object has no attribut...
ERROR tests/radiation_transport/test_advective_transport.py::TestChargedParticleRecursionDN::test_recursion - AttributeError: 'list' object has no attribute 'T'
ERROR tests/radiation_transport/test_advective_transport.py::TestChargedParticleRecursionDN::test_analyse_DN - AttributeError: 'list' object has no attribute 'T'
```

## Proposed solution

Fix tests

## Alternative solutions

We need to update at some point but we could possibly wait

## Additional context

previously we were blocked by an old 3D plotting hack we had

### PR DESCRIPTION
**Pull request by hsaunders1904**
## Linked Issues

Closes #994 

## Description

Bumps Matplotlib version to 3.5.1 and fixes some tests that were failing due to the upgrade.

The majority of the broken tests were failing because of an API change to the private module `matplotlib._contour`, which we use to generate contours in `equilibria.find.get_contours`. I suppose this is just one of the risks of using a private module/class/function. It may be worth thinking about if we can generate these contours without the use of matplotlib internals, but I couldn't find an obvious alternative after a quick google. This fixes things for now.

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `flake8` and `black .`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Review by je-cook — APPROVED** [review]
Looks great, I like the test improvement. Pity about the contour stuff, maybe open an issue about it?

**Review by je-cook — CHANGES_REQUESTED** [review]
oh actually can you remove the pinning in the dependabot config here https://github.com/Fusion-Power-Plant-Framework/bluemira/blob/76e9630b544fd8d6c3d8da5c6a0df37e6ecc4405/.github/dependabot.yml#L10?

**Review by je-cook — APPROVED** [review]
Thanks! Failure is because of #999 rebase once thats in should fix it

**Comment by CoronelBuendia** [comment]
Please check pytest --reactor --plotting-on ;)

**Comment by je-cook** [comment]
> Please check pytest --reactor --plotting-on ;)

Ahh good point I've got quite a few failures left there!

**Comment by hsaunders1904** [comment]
> > Please check pytest --reactor --plotting-on ;)
> 
> Ahh good point I've got quite a few failures left there with the full `pytest --reactor --longrun --private --plotting-on`!

There seem to be several tests that fail on `develop` with the old Matplotlib (3.3.4).

These fail on `develop` (with Matplotlib 3.3.4):
```
FAILED tests/structural/test_crosssection.py::TestIbeam::test_plot - AttributeError: 'BluemiraFace' object has no attribute 'plot'
FAILED tests/structural/test_model.py::TestCompoundDeflection::test_fixedfixed - AttributeError: 'Element' object has no attribute 'max_deflection'
FAILED tests/structural/test_model.py::TestCompoundDeflection::test_cantilever - AttributeError: 'Element' object has no attribute 'max_deflection'
FAILED tests/structural/test_model.py::TestGravityLoads::test_angled_cantilever - AttributeError: 'Element' object has no attribute 'max_deflection'
FAILED tests/structural/test_symmetry.py::TestCyclicSymmetry::test_symmetry - AttributeError: 'Element' object has no attribute 'max_deflection'
```

These pass on `develop`:
```
FAILED tests/geometry/test_deprecated_loop.py::Test3Dplotting::test_looks_good - RecursionError: maximum recursion depth exceeded
FAILED tests/geometry/test_deprecated_loop.py::Test3Dplotting::test_edges_again - RecursionError: maximum recursion depth exceeded
```

I'll sort out the new failures in this PR, but open a new issue for the others.

It feels to me that we should be running the plotting tests in the CI. They're useful as they interact with our code in ways users are likely to. Could the `--plotting-on` flag just switch on matplotlib's interactive backend for the plots? Or is it made too complicated by the 3D CAD display?

Also, I can't run the private tests as "`Data directory not found`". Is there some documentation on how I can set my environment up to run those tests?

**Comment by je-cook** [comment]
> These fail on `develop` (with Matplotlib 3.3.4):
> 
> ```
> FAILED tests/structural/test_crosssection.py::TestIbeam::test_plot - AttributeError: 'BluemiraFace' object has no attribute 'plot'
> FAILED tests/structural/test_model.py::TestCompoundDeflection::test_fixedfixed - AttributeError: 'Element' object has no attribute 'max_deflection'
> FAILED tests/structural/test_model.py::TestCompoundDeflection::test_cantilever - AttributeError: 'Element' object has no attribute 'max_deflection'
> FAILED tests/structural/test_model.py::TestGravityLoads::test_angled_cantilever - AttributeError: 'Element' object has no attribute 'max_deflection'
> FAILED tests/structural/test_symmetry.py::TestCyclicSymmetry::test_symmetry - AttributeError: 'Element' object has no attribute 'max_deflection'
> ```

as you say we should test the plotting on the CI without a front end

> I'll sort out the new failures in this PR, but open a new issue for the others.

Sounds good

> It feels to me that we should be running the plotting tests in the CI. They're useful as they interact with our code in ways users are likely to. Could the `--plotting-on` flag just switch on matplotlib's interactive backend for the plots? Or is it made too complicated by the 3D CAD display?

I think at least for the mpl stuff it should be straight forward, and I think we should. We may be able to make it happen for the CAD display maybe as part of fixing #997

**Comment by hsaunders1904** [comment]
Issue to fix plotting tests broken in develop: https://github.com/Fusion-Power-Plant-Framework/bluemira/issues/1002

**Review by je-cook — APPROVED** [review]

**Pull request merged**
