### PR TITLE
Initial setup for readthedocs

### LINKED ISSUE #537: Publish documentation to readthedocs
## Description of issue / requirement to address

Now that we are public we can start to use neat OS tools (for free), like https://readthedocs.org. We should set up a project in readthedocs for bluemira, with at least two maintainers, and publish our documentation there.

## Proposed solution

Use readthedocs to host our documentation.

## Alternative solutions

We could use GitHub pages, but I personally do not like how you have to make commits of the built documentation to branches / a parallel repo. RTD also gives nice flexibility for building across different branches / versions.

### PR DESCRIPTION
**Pull request by DanShort12**
## Linked Issues

Closes #537

## Description

Initial set up for readthedocs.

## Interface Changes

N/A

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `flake8` and `black .`
- [x] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Comment by DanShort12** [comment]
@je-cook and @CoronelBuendia added as maintainers in https://readthedocs.org. Docs from this branch can be viewed at https://bluemira.readthedocs.io/en/danshort12-read-the-docs/ (we should remove the docs for the branch when we're done with this PR).

**Comment by je-cook** [comment]
Do we want to double check some of the docs read well eg for me this all comes out as latex not actual formulas (it could just be me)

https://bluemira.readthedocs.io/en/danshort12-read-the-docs/autoapi/bluemira/balance_of_plant/steady_state/index.html#bluemira.balance_of_plant.steady_state.BalanceOfPlant

**Comment by DanShort12** [comment]
Yea, it looks fine for me (apart from the scrolling...) I guess we could handle that by splitting long equations across a few lines? I've done a click though some of the docs - I think generally they need a bit of a tidy up and expanding in a few areas... could be that we get them published and continue from there as long as there aren't any bits that are glaringly broken?

**Comment by je-cook** [comment]
yeah sure

**Review by je-cook — APPROVED** [review]

**Pull request merged**
