### PR TITLE
✨ Create a citation file

### LINKED ISSUE #107: Add CITATION.cff
**Is your feature request related to a problem? Please describe.**
It should be clear how we expect people to cite bluemira in their work.

**Describe the solution you'd like**
GitHub has implemented a summary of the citation file on the front page of a project. We should add a citation file so that it gets picked up by this new mechanism.

**Describe alternatives you've considered**
We could add a citation string on the README, but the GitHub in-built mechanism is cleaner.

### PR DESCRIPTION
**Pull request by je-cook**
## Linked Issues

Closes #107 

## Description

Created from https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md.
May want to change authors from bluemira team to actual names

## Checklist

I confirm that I have completed the following checks:

- [X] Tests run locally and pass `pytest tests --reactor`
- [X] Code quality checks run locally and pass `flake8` and `black .`
- [X] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Comment by je-cook** [comment]
to view how this works go to view file and then click the root directory . You will see a cite this repo in the right panel. I think we may need to add a preferred citation but there are currently a few issues

- If we used preferred citation only 1 is alowed
- the repo is no longer cited in the link if we use preferred citation

The other option seems to be creating a citation.bib file that the widget will link to. If we do that we could copy the bib file to the working directory on running

**Comment by CoronelBuendia** [comment]
> to view how this works go to view file and then click the root directory . You will see a cite this repo in the right panel. I think we may need to add a preferred citation but there are currently a few issues
> 
>     * If we used preferred citation only 1 is alowed
> 
>     * the repo is no longer cited in the link if we use preferred citation
> 
> 
> The other option seems to be creating a citation.bib file that the widget will link to. If we do that we could copy the bib file to the working directory on running

Perhaps a good example to follow: https://github.com/boutproject/BOUT-dev/blob/master/CITATION.cff

The decision there seems to be to list all the contributors and point to a single paper. Seeing as we will have publications on BLUEMIRA in future, we can add that paper later. For now, if we have to pick one, I would pick none, and just point the users to the README, where the relevant publications are already listed.

Listing all the actual contributors (i.e. not just members on the repo) in the CITATION.cff seems like the best way forward to me, as it acknowledges the work of those who weren't around when those publications were written. If the users want an actual publication to cite (and they usually do) they are in the README, and in future the one BLUEMIRA paper which we can add if and when it gets published.

**Comment by DanShort12** [comment]
In principle I agree with @CoronelBuendia that listing the contributors is a fair way to do this - I suspect a lot of what is in the existing MIRA / BLUEPRINT papers wouldn't align greatly with the current bluemira functionality. However, it does mean that the citation file would need to be maintained as new contributors are added, and we would need to create a doi on zenodo to make the releases citable (when we have a first release).

**Comment by je-cook** [comment]
oops no that didnt work

**Review by DanShort12 — APPROVED** [review]
Looks good to me.

**Review by CoronelBuendia — APPROVED** [review]

**Pull request merged**
