### PR TITLE
put the Monte Carlo back in the fuel cycle model

### PR DESCRIPTION
**Pull request by CoronelBuendia**
## Linked Issues

Took me a while to debug this... I'm not sure of the motivations behind lumping fixed random seeds in an enum, but I can say for sure that it means the fuel cycle model can no longer be run Monte Carlo.

Closes #{ID}

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `pre-commit run --from-ref develop --to-ref HEAD`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Comment by je-cook** [comment]
The reasoning was reproducability of results. You need to be able to set the random seed to have results that are reproduceable. I feel removing the seeds is possibly the wrong approach. 

The seed should just be a starting point for generation and if we need multiple starting points we should use a specific seed (that can be changed by the user) and we should jump down the generation sequence. We can also change the generation alogorithm from the default [PGC64](https://numpy.org/doc/stable/reference/random/generator.html) and use something like the [mersenne twister](https://numpy.org/doc/stable/reference/random/bit_generators/mt19937.html#numpy.random.MT19937). The jumped function should be enough to move us down the generation sequence far enough to accomplish monte carlo runs which is what I have done previously.

**Comment by CoronelBuendia** [comment]
> The reasoning was reproducability of results. You need to be able to set the random seed to have results that are reproduceable. I feel removing the seeds is possibly the wrong approach.
> 
> The seed should just be a starting point for generation and if we need multiple starting points we should use a specific seed (that can be changed by the user) and we should jump down the generation sequence. We can also change the generation alogorithm from the default [PGC64](https://numpy.org/doc/stable/reference/random/generator.html) and use something like the [mersenne twister](https://numpy.org/doc/stable/reference/random/bit_generators/mt19937.html#numpy.random.MT19937). The `jumped` function on the MT19937 should be enough to move us down the generation sequence far enough to accomplish monte carlo runs which is what I have done previously.

The intended use of the fuel cycle model is as in the example, where the random seed is set at the outermost-level and results are reproducible for the same set of inputs. Right now the example does not work as intended: it just repeats the same results n times. The fact that these modifications just hard-code the random seed inside some utility functions, without taking an optional argument that could potentially override it, means that the fuel cycle model cannot be run Monte Carlo.

It's a bug in functionality that previously worked. This PR fixes it.

What you're talking about is a potential improvement and I have nothing against it, per se.

**Comment by je-cook** [comment]
That may be true but while fixing it, it should be fixed properly

**Comment by CoronelBuendia** [comment]
> That may be true but while fixing it, it should be fixed properly. In fact I would consider the inability to reproduce results in itself a bug

Was there such an inability in the user-facing API? I wasn't aware... The example used to produce reproduce-able results, at least per machine (I never checked across machines). If you want, when I get back to this branch I can run the example as is, and you run it on your machine are see what we get?

**Comment by je-cook** [comment]
Please see #3742 for my implementation of this that hopefully fixes both bugs

**Pull request closed without merging**
