### PR TITLE
Add EU-DEMO cryostat thermal shield

### LINKED ISSUE #582: Add builder for EU-DEMO thermal shield
## Description of issue / requirement to address

We need a `Builder` for the thermal shield, ultimately including:
*  vacuum vessel thermal shield (VVTS)
*  ports
*  cryostat thermal shield

## Proposed solution

Add a build for an EU-DEMO-like thermal shield

## Alternative solutions
N/A

## Additional context

Might be easiest to get started on just the cryostat thermal shield, seeing as we don't have a vacuum vessel for EU-DEMO yet.

### PR DESCRIPTION
**Pull request by CoronelBuendia**
## Linked Issues
Requires #702 
Closes #582 (will pick up VVTS and ports in a future issue

## Description

Adds a thermal shield builder, which at present just builds the cryostat TS.

## Interface Changes

N/A

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `flake8` and `black .`
- [x] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Review by DanShort12 — APPROVED** [review]
Looks good to me with the new interface. I've put together #658 to allow cut-through builds, so might be worth getting that in and then adjusting this one to build through a specified number of degrees (or could put in an optional `degree` parameter to match that interface already. Otherwise happy for this to go in first and can tweak the xyz build to account for that after this merge.

**Comment by CoronelBuendia** [comment]
> Looks good to me with the new interface. I've put together #658 to allow cut-through builds, so might be worth getting that in and then adjusting this one to build through a specified number of degrees (or could put in an optional `degree` parameter to match that interface already. Otherwise happy for this to go in first and can tweak the xyz build to account for that after this merge.

Yeah, let's get #658 in first.

**Comment by CoronelBuendia** [comment]
All up to date locally but I'm having a problem with a boolean operation failure which I'd like to get right before putting this in.

**Comment by je-cook** [comment]
Any more needed here before merge @CoronelBuendia?

**Comment by je-cook** [comment]
ahh sorry #687

**Comment by CoronelBuendia** [comment]
should be ready now

**Pull request merged**
