### PR TITLE
Swap out scipy optimiser for NLOpt in FEM fixed boundary equilibria magnetic axis finding

### PR DESCRIPTION
**Pull request by CoronelBuendia**
## Linked Issues

Partially addresses #1253

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `flake8` and `black .`
- [x] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Comment by CoronelBuendia** [comment]
@ivanmaione, I actually just tried this with the FE derivatives of psi, with something along the lines of:

```python
dpsi_dx = dolfin.project(self.psi.dx(0))
dpsi_dz = dolfin.project(self.psi.dx(1))

...
grad[0] = -dpsi_dx(*x)
grad[1] = -dpsi_dz(*x)
```
Obviously there's a bit of an overhead in doing this project (about 0.5 seconds at the start and 8-9 ms thereafter), and to my surprise it did not perform any better (actually slightly worse!). I guess for psi it is such a smooth function that numerical gradients are not so bad. Or possibly that the FE derivatives are not so good, maybe I need a different order or something. Either way, so far I don't see gains with the "analytical" gradient.

**Comment by ivanmaione** [comment]
> 

Since self.psi is already a function, unless it is not necessary to project it on a different space, the projection should not be necessary (i.e. you already have access to `grad` being calling self.psi.dx). In this way, one would gain that 0.5s.

**Comment by CoronelBuendia** [comment]
> > 
> 
> Since self.psi is already a function, unless it is not necessary to project it on a different space, the projection should not be necessary (i.e. you already have access to `grad` being calling self.psi.dx). In this way, one would gain that 0.5s.

Right, but I couldn't find a way to evaluate `self.psi.dx` at a point. Is there a way?

**Comment by ivanmaione** [comment]
> > Since self.psi is already a function, unless it is not necessary to project it on a different space, the projection should not be necessary (i.e. you already have access to `grad` being calling self.psi.dx). In this way, one would gain that 0.5s.
> 
> Right, but I couldn't find a way to evaluate `self.psi.dx` at a point. Is there a way?

You are right. Unfortunately, I don't think there is a faster way to do that.

**Review by ivanmaione — APPROVED** [review]

**Pull request merged**
