### PR TITLE
Remove functionality from `_deprecated_geometry` 

### LINKED ISSUE #1323: Move `_deprecated_` geometry modules that we need to private module
## Description of issue / requirement to address

We should make a plan to remove the `_deprecated_` modules in geometry or reuse parts as needed.

## Proposed solution

Remove `_deprecated_` modules

## Alternative solutions

Leave deprecated modules, essentially flagging them not to be used for new code

## Additional context

`_deprecated_` modules have been around for a while

### PR DESCRIPTION
**Pull request by CoronelBuendia**
## Linked Issues

Partially addresses #1323

## Description

What is your PR trying to achieve? How did you go about achieving it?

## Interface Changes

If you've had to update an interface or introduce a new interface as part of your change then let us know here.

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `flake8` and `black .`
- [x] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Comment by je-cook** [comment]
Does this close #1323 because some of `_deprecated_tools.py` still exists (even if stripped down)?

**Comment by CoronelBuendia** [comment]
> Does this close #1323 because some of `_deprecated_tools.py` still exists (even if stripped down)?

Fair. It closes it as far as it can be without robust CAD or primitive offsetting algorithms.

**Comment by je-cook** [comment]
Sure, we can take it off the milestone nearer to the time (or punt it) as we see fit

**Review by je-cook — APPROVED** [review]
Looks good to me

**Pull request merged**
