### PR TITLE
Fix units and unit-conversion factors

### LINKED ISSUE #2853: Papercut: Remove *_TO_* constants from bluemira.base.constants
## Describe the papercut

There are 5 variables:
1. `EV_TO_J`
2. `J_TO_EV`
3. `AMU_TO_KG`
4. `YR_TO_S`
5. `S_TO_YR`

1-3 are used in bluemira.plasma_physics while 4-5 are used in bluemira.fuel_cycle.
Where these constants are used multiplicatively, e.g. `(e_dt * EV_TO_J)`, they can be replaced by `raw_uc(e_dt, 'eV', 'J')` for easier comprehension.

## Suggested fix/Desired result

No more `*_TO_*` constants left in bluemira.base.constants. `raw_uc`; Manually find-and-replace all instances of the variables A_TO_B above and replace with raw_uc(..., 'A', 'B'), so that they become more readable/ easier to debug.

## Alternative fix
N/A

## Estimated difficulty

Easy

Variable 1-3 were only used a maximum of twice per file, so only minimal change would be required, and should result in reduction in number of lines of code (fewer imports).

Variable 4-5 were used many more times in fuel cycle, but it should also be an easy find-and-replace job.

### LINKED ISSUE #2857: Temperature given in eV instead of keV or K in 3 files.
## Describe the papercut

When plasma temperature is specified in non-SI unit, it's almost always given as [keV]; except for 3 files:

- bluemira.codes.process._solver.get_species_data outputs temperature `tref` in eV.
- bluemira.plasma_physics.rules_of_thumb.estimate_loop_voltage takes in electron temperature on axis `T_e` in eV.
- bluemira.plasma_physics.collisions.spitzer_conductivity takes in electron temperature on axis `T_e` in eV.

## Suggested fix
Convert all of the above from eV to keV instead, using bluemira.base.constants.raw_uc when appropriate.

## Other modules affected/ dependencies
No other modules affected.
bluemira.plasma_physics.rules_of_thumb.estimate_loop_voltage uses bluemira.plasma_physics.collisions.spitzer_conductivity.

### PR DESCRIPTION
**Pull request by OceanNuclear**
## Linked Issues

Closes #2853 with caveats: YR_TO_S and S_TO_YR cannot be removed completely as bluemira/plasma_physics/tools.py uses them, and cannot be converted to raw_uc there due to numba.jit.

Closes #2857 with caveats: get_species_data needs to be overhauled if this change were to be made, so it has been left unchanged, and may be ultimately solved in issue #2890.

## Description

Solves issue #2853 and #2857 simultaneously, so all temperature units are in keV or K (as opposed to a mix of eV/keV/K); and no more conversion multiplies (`*_TO_*`) are required.

## Interface Changes

bluemira.plasma_physics.rules_of_thumb.estimate_loop_voltage now takes in electron temperature in keV instead of eV.
bluemira.plasma_physics.collisions.spitzer_conductivity now takes in electron temperature in keV instead of eV.

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `pre-commit run --from-ref develop --to-ref HEAD`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Comment by OceanNuclear** [comment]
(Manually checked and confirmed that this change does not lead to conflict in any other branches)

**Comment by je-cook** [comment]
I'm only starting going through this one. My first thought is that the reduction in the use of the S_TO_YR and YR_TO_S will increase the number of calculations that have to be undertaken. In one instance as the conversion happens within a for loop its a many times increase.

Most of the other conversions are fairly sensible but I think there is no need to reduce so drastically the time conversions especially as its so widely used

**Comment by OceanNuclear** [comment]
I thought the number of calculations would be the same across 
```python
raw_uc(delta_t, "yr", "s")
```
and 
```python
delta_t * YR_TO_S
```
? As raw_uc does the multiplication under the hood, plus a few other unit lookup calls inside pint.

The only place where this might be a significant a problem is in the for-loop inside EUDEMOFuelCycleModel.tbreed, but I thought that's not a function needing optimization because it re-calculated the temporary variable `(YR_TO_S * dt)` four times in a row, so I thought my method of initializing the local variable `dts` would still be faster as it removes the need for 3 multiplications.

**Comment by je-cook** [comment]
I agree with your second point but your first point `raw_uc` has at least 2 extra operations; decoding of unit strings to numbers. Therefore if we only have to do that once for some speed relevant code thats a good thing especially as we can't remove YR_TO_S completely anyway. 

Its only in that usecase no need to apply the logic everywhere

**Review by je-cook — APPROVED** [review]
Great, thanks!

**Pull request merged**
