### PR TITLE
🔥 Delete BLUEPRINT

### LINKED ISSUE #310: Remove BLUEPRINT as much as possible
## Description of issue / requirement to address

We need to dissolve the soon to be deprecated BLUEPRINT repository as much as possible prior to open source release.

## Proposed solution

Piece by piece, replace BLUEPRINT functionality with bluemira implementations. Remove any unused functionality, remove any private data.

* [x] equilibria
* [x] charged particle heat flux solver
* [x] 0-D BoP model
* [x] structural module
* [ ] geometry
* [ ] cad
* [ ] base
* [x] materials
* [ ] nova
* [ ] systems
* [ ] utilities
* [x] costs
* [ ] neutronics
* [ ] cli

## Additional context

This is a wide ranging issue and partly a placeholder to make sure we don't forget to do this prior to open-sourcing.

### PR DESCRIPTION
**Pull request by je-cook**
## Linked Issues

Closes #310 

## Description

This PR deletes most occurances of the word BLUEPRINT and all BLUEPRINT files. The branch `STEP_deprecated` will contain this data for a while longer to smooth their transition to only bluemira.

TODO

- [X] deprecated_boolean replacement  ( `from BLUEPRINT.geometry.shell import Shell`) #931 
- [X] deprecated_loop still has a BLUEPRINT import in the instance check (as it is not at the top level we could leave it for a bit...?) (See comment below)
- [ ] Remake documentation/source/EU-DEMO_params.rst  - non blocking (not sure we even need to?)
- [ ] Remake cli.py - non blocking #927

## Interface Changes

Bye bye BLUEPRINT :smiling_face_with_tear: 

## Checklist

I confirm that I have completed the following checks:

- [x] Tests run locally and pass `pytest tests --reactor`
- [x] Code quality checks run locally and pass `flake8` and `black .`
- [x] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Comment by CoronelBuendia** [comment]
Maybe for the instance check you could check the `.__class__.__name__ == "Loop"`?

**Review by hsaunders1904 — APPROVED** [review]
Always good to see almost a million lines gone!

You've probably seen it, but doing a grep for BLUEPRINT over the repo, I came across `bluemira.equilibria.equilibrium.get_flux_through_point`, which apparently is wrong, but only kept around because it's used in BLUEPRINT. Can that be removed?

**Comment by je-cook** [comment]
Ok all done @hsaunders1904 @CoronelBuendia. I think a review from the pair of you should cover the lot

**Comment by CoronelBuendia** [comment]
There are a lot of get_bluemira_paths in the tests that depend on the test data folder being tests/bluemira/.../test_data THink you might need to change them to get the tests to pass.

**Pull request merged**
