### PR TITLE
⬆️ 👽 Bump PROCESS version 

### PR DESCRIPTION
**Pull request by je-cook**
## Description

PROCESS v3.0.2 update. Has some small API changes due to obsolete and removed functionality

## Interface Changes

See https://github.com/ukaea/PROCESS/releases/tag/v3.0.2

## Checklist

I confirm that I have completed the following checks:

- [ ] Tests run locally and pass `pytest tests --reactor`
- [ ] Code quality checks run locally and pass `pre-commit run --from-ref develop --to-ref HEAD`
- [ ] Documentation built locally and checked `sphinx-build -W documentation/source documentation/build`

### CODE REVIEW

**Comment by athoynilimanew** [comment]
I am trying to use the PROCESSTemplateBuilder for my reactor design. I keep getting the following error: 

  File "<path to my bluemira>/bluemira/codes/process/template_builder.py", line 295, in make_inputs
    return ProcessInputs(
TypeError: __init__() got an unexpected keyword argument 'fradpwr'`

**Comment by athoynilimanew** [comment]
Need to add additional switches in `bluemira.codes.process._model_mapping`:

- [ ] * `idia`: Diamagnetic Current Scaling, 
- [ ] * `ips`: Pfirsch-Schluter Current Scaling
- [ ] * `itart`: Switch for Spherical Tokamak models
- [ ] * `i_r_cp_top`: Switch selecting the TF CP is parametrization 
- [ ] * `i_tf_tresca`: Switch for TF coil conduit TRESCA stress criterion
- [ ] * `itartpf`: Switch for Spherical Tokamak PF models
- [ ] * `i_bldgs_size`: Switch between building size estimates
- [ ] * `ifueltyp`: Switch (0: Treat Blanket, Divertor, FW and CD Equipment as Capital Cost)
- [ ] * `lsa `: Level of Safety Assurance Switch (2: In-Between)
-

**Comment by je-cook** [comment]
@athoynilimanew thanks for listing them out here is the changes:

already existed in Iteration variables but werent added to inputs:
dr_tf_wp
fradpwr

already existing model but werent added to inputs:
i_r_cp_top

Existed as input but not models
itart
itartpf
ifueltyp

New Models
idia
ips
i_tf_tresca
i_bldgs_size

Already existed everywhere
lsa

**Review by oliverfunk — APPROVED** [review]
Can't see anything wrong with it :D

**Pull request merged**
